Document: tidy-html5
Title: Debian tidy-html5 Manual
Author: <insert document author here>
Abstract: This manual describes what tidy-html5 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tidy-html5/tidy-html5.sgml.gz

Format: postscript
Files: /usr/share/doc/tidy-html5/tidy-html5.ps.gz

Format: text
Files: /usr/share/doc/tidy-html5/tidy-html5.text.gz

Format: HTML
Index: /usr/share/doc/tidy-html5/html/index.html
Files: /usr/share/doc/tidy-html5/html/*.html
